services:
  - type: web
    name: campus-connect-backend
    env: node
    plan: free
    repo: <YOUR_GITHUB_ORG/REPO>
    branch: main
    path: backend
    buildCommand: npm install
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        value: ""
      - key: JWT_SECRET
        value: ""
      - key: NODE_ENV
        value: production
